version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2019 Preview
- Ubuntu1804
configuration:
- Debug
- Release
platform:
- x86
- x64
- ARM
build_script:
- cmd: >-
    mkdir build
    cd build
    cmake ..
    cmake --build . --config %configuration%
- sh: >-
    mkdir build
    cd build
    cmake ..
    cmake --build . --config %configuration%
test_script:
- cmd: ctest -C %configuration% --output-on-failure
- sh: ctest -C %configuration% --output-on-failure
notifications:
- provider: Email
  to:
  - zifter.ai@gmail.com
  subject: '[Appveyor] CI expression_fetcher'
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
